<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.typekit.net/ubv0wui.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css">
    <title>Intelligent Mind</title>
    <div class="d-flex">
        <h1>Intelligent Mind with
        <small>OpenAI</small>
        </h1>
    </div>

</head>


