<html lang="en">
<head>
    <link rel="stylesheet" href="../../css/bootstrap.min.css">
    <link rel="stylesheet" href="../../css/style.css">
    <link rel="stylesheet" href="https://use.typekit.net/ubv0wui.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Intelligent Mind</title>

</head>

    <div>
        <div class="d-flex row">
            <div>
                <div class="row ">
                    <button class="btn btn-primary col-1 mx-2 w-auto" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample" aria-controls="offcanvasExample">
                        ≡
                    </button>
                    <h4 class="col-1 navigation">Menu</h4>
                    <div class="d-flex  col-1">
                        <h1 class="w-auto col-5">Intelligent Mind with <small>OpenAI</small></h1>
                    </div>
                </div>
            </div>


        </div>
        <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
            <div class="offcanvas-header">
                <h4 class="offcanvas-title" id="offcanvasExampleLabel">Other Conversations</h4>
                <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>

            <div class="text-center">
                <p>
                    <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                        New Conversation
                    </button>
                </p>
                <div class="collapse" id="collapseExample">
                    <div class="card card-body text-white bg-dark mb-0">
                        <form method="post" action="<?php echo $_SERVER['PHP_SELF']?>" onload="refresh()">
                            <label for="chatname">Chat name</label>
                            <input class="form-control" id="chatname" placeholder="enter chat name" name="newConversationName" value="<?php if (isset($_POST['newConversationName'])){ echo $_POST['newConversationName'];}?>"/>
                            <br/>
                            <label for="submission">Chat name</label>
                            <input class="btn btn-success" id="submission" type="submit" value="newChat" name="newChat"/>
                        </form>
                    </div>
                </div>

                <div>
                    <?php foreach ($view->chats as $chat) :?>
                        <p><?php echo $chat->getChat();?></p>
                    <?php endforeach;?>
                </div>
            </div>
        </div>

    </div>
<body class="container-fluid vh-100">

