<div>
    <button class="btn btn-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample" aria-controls="offcanvasExample">
       ≡
    </button>
    <h6 style="display: inline;">See Conversation History</h6>
</div>
<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
  <div class="offcanvas-header">
    <h4 class="offcanvas-title" id="offcanvasExampleLabel">Conversation History</h4>
    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
    <div>
        <form method="post" action="<?php echo $_SERVER['PHP_SELF']?>">
            <input type="text" id="user-search" placeholder="Search..." name="searchMsg" value="<?php if (isset($_POST['searchMsg'])){ echo $_POST['searchMsg'];}?>">
        </form>
    </div>
</div>